---
title: "boxcox_analysis"
author: "Nils Wendel Heinrich"
date: "2024-06-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(dplyr)
library(arrow)
library(MASS)

```

```{r data, include=FALSE}

setwd('/Users/heinrich/Projects/CogSci2024_analysis/')

all_fixations <- read_feather("data/allFixations.arrow")
fovActionGoals <- read_feather("data/foveatedActionGoals.arrow")

all_fixations <- filter(all_fixations, fixation_duration >= 0.0125)
fovActionGoals <- filter(fovActionGoals, fixation_duration >= 0.0125)

```

##All fixations
```{r box_cox_allFix_fixDur, include=FALSE}

Lambda <- boxcox(lm(all_fixations$fixation_duration ~ 1))

Lambda$x[which(Lambda$y == max(Lambda$y))]

```
lambda, the estimated value is near to 0, implies log transform.


```{r box_cox_allFix_dist, include=FALSE}

Lambda <- boxcox(lm(all_fixations$distance_to_spaceship ~ 1))

Lambda$x[which(Lambda$y == max(Lambda$y))]

```
lambda, the estimated value is near to 0, again implying log transformation.

##Foveated Action Goals
```{r box_cox_fovActionGoals_fixDur, include=FALSE}

boxcox(lm(fovActionGoals$fixation_duration ~ 1))

```
lambda, the estimated value is near to 0, implies log transform.


```{r box_cox_fovActionGoals_distAgent, include=FALSE}

Lambda <- boxcox(lm(fovActionGoals$distance_to_spaceship ~ 1))

Lambda$x[which(Lambda$y == max(Lambda$y))]

```
lambda, the estimated value is near to -1, implies 1/x transformation.

```{r box_cox_fovActionGoals_distObstacle, include=FALSE}

boxcox(lm(fovActionGoals$Dist_to_closest_obstacles ~ 1))

```
lambda, the estimated value is near to 0, implies log transform.

